influxdbconninfo:
  url: http://192.168.10.59:8086
  username: root
  password: root
  database: loudi
  retention: rp_30_days

# 以上是 influxDB 的连接配置信息
#建议格式： spring.influx.url=http://xxx.xxx.xxx.x

#spring:
#  influx:
#    url: http://192.168.10.59:8086
#    user:
#    password:
#    database: iotbigdata

server:
  #项目网络的端口号
  port: 8008
